// src/vue/app.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watchEffect } from "vue";
import { cachedRef } from "./hooks";
import Modal from "./modal.vue";
import Sampleviz from "./samplewave.vue";
import { loadSource } from "../react/loader";
import { loadCachedSamples, limit } from "./lib";
import Assign from "./assign.vue";

declare global {
  interface Window {
    webkitAudioContext: typeof AudioContext;
  }
}
export type BufferState = { [name: string]: AudioBuffer };

export type SampleT = {
  key: string;
  bufferid: string;
  active: boolean;
  held: boolean;
  begin: number;
  end?: number;
};
export type SamplesT = {
  [id: string]: SampleT | null;
};

const createEmpty = () => {
  const empty: SamplesT = {};
  "abcdefghijklmnopqrstuvwxyz".split("").forEach((letter) => {
    empty[letter] = null;
  });
  return empty;
};

const audioContext = new (window.AudioContext || window.webkitAudioContext)();
const buffers = ref<BufferState>({});
const samples = cachedRef<SamplesT>("sample-keys", createEmpty());
//
const ui = ref<{
  sample: SampleT | null;
  modal: { type: string; value?: string } | null;
  assignBuffer: string;
  edit: "begin" | "end" | null;
  loading: boolean;
}>({
  sample: null,
  modal: null,
  assignBuffer: "",
  edit: null,
  loading: false,
});

onMounted(async () => {
  // set loading state
  ui.value.loading = true;
  const _src = await loadCachedSamples();
  if (_src) buffers.value = _src;
  ui.value.loading = false;
});

const sources: { [id: string]: AudioBufferSourceNode | null } = {};

const samplekeys = "qwertyuiopasdfghjklzxcvbnm";

const keydown = (ev: KeyboardEvent) => {
  const { key } = ev;

  // first modal
  if (ui.value.modal) {
    if (ui.value.modal?.type === "assign") {
      samples.value[key] = {
        key,
        active: true,
        begin: 0,
        bufferid: ui.value.assignBuffer,
        held: false,
      };
      ui.value.modal = null;
      return;
    }
    if (ui.value.modal?.type === "copy") {
      if (ui.value.sample && !samples.value[key]?.active) {
        samples.value[key] = { ...ui.value.sample, key };
        ui.value.modal = null;
        return;
      }
      return;
    }
  }

  //  play sample
  if (samplekeys.includes(key)) {
    const sample = samples.value[key];
    if (!sample?.active || sample?.held) return;
    sources[key]?.start(audioContext.currentTime, sample.begin);
    sample.held = true;
    // open in viz - if viz is empty
    if (!ui.value.sample) viewSample(samples.value[key]);
    return;
  }

  // sample edit
  if (ui.value.edit && key.startsWith("Arrow")) {
    const sample = ui.value.sample;
    const edit = ui.value.edit;
    if (!edit || !sample) return;
    const fine = ev.shiftKey ? 0.5 : 1;
    const keyVals: { [k: string]: number } = {
      ArrowUp: 0.01,
      ArrowDown: -0.01,
      ArrowLeft: -0.1,
      ArrowRight: 0.1,
    };
    if (!keyVals[key]) return;
    let next = sample.begin + keyVals[key] * fine;
    if (next < 0) next = 0;
    sample[edit] = next;
  }

  // close sample
  if (ui.value.sample?.active) {
    if (key === "Escape") {
      ui.value.sample = null;
      ui.value.edit = null;
    }
  }
};

const keyup = (ev: KeyboardEvent) => {
  const { key } = ev;
  const sample = samples.value[key];
  if (!sample) return;
  // stop
  sources[key]?.stop();
  sample.held = false;
  if (!sample?.active) return;

  const buffer = buffers.value[sample.bufferid];
  const source = loadSource(buffer, 1.0);
  sources[key] = source;
};

onMounted(() => {
  window.addEventListener("keydown", keydown);
  window.addEventListener("keyup", keyup);
});

onUnmounted(() => {
  window.removeEventListener("keydown", keydown);
  window.removeEventListener("keyup", keyup);
});

const openSampleModal = () => {
  ui.value.modal = {
    type: "assign",
  };
};

const viewSample = (sample: SampleT | null) => {
  if (!sample?.active) return;
  ui.value.sample = sample;
};

const removeKey = () => {
  if (ui.value.sample) ui.value.sample.active = false;
};

const openCopyModal = () => {
  ui.value.modal = {
    type: "copy",
  };
};
</script>
<template>
  <header>
    <h1 class="h-10">Audio Sampler</h1>
  </header>
  <main class="min-h-[calc(100vh-2.5rem)] grid grid-rows-[1fr_auto]">
    <div class="relative">
      <Assign :ui="ui" :buffers="buffers" @assign="openSampleModal" />
      <section
        class="view absolute inset-0 bg-[var(--bg)]"
        v-if="ui.sample?.active"
      >
        <div class="flex justify-between">
          <h2 class="text-2xl">{{ ui.sample.key }}</h2>
          <button @click="ui.sample = null">Close</button>
        </div>
        <p>{{ ui.sample?.bufferid }}</p>
        <div>
          <button @click="removeKey">remove</button>
        </div>
        <Sampleviz :buffer="buffers[ui.sample.bufferid]" :sample="ui.sample" />
        <div class="flex justify-between">
          <div>
            <button v-if="ui.edit === 'begin'" @click="ui.edit = null">
              finish
            </button>
            <button v-else @click="ui.edit = 'begin'">Edit begin</button>
          </div>
          <div>
            <button v-if="ui.edit === 'end'" @click="ui.edit = null">
              finish
            </button>
            <button v-else @click="ui.edit = 'end'">Edit End</button>
          </div>
        </div>
        <div class="flex">
          <button @click="openCopyModal">copy</button>
        </div>
      </section>
    </div>

    <section class="w-4/5 wmax-w-[900px] mx-auto">
      <div
        class="flex gap-2"
        v-for="row in ['qwertyuiop', 'asdfghjkl;', 'zxcvbnm,.']"
      >
        <button
          class="grow aspect-square border border-white p-2 box-content"
          v-for="k in row"
          :class="
            samples[k]?.held
              ? ' bg-blue-400 bg-opacity-50'
              : samples[k]?.active
              ? ' bg-white bg-opacity-10 '
              : ''
          "
          @click="viewSample(samples[k])"
        >
          {{ k }}
        </button>
      </div>
    </section>
    <section>
      <Modal :isOpen="ui.modal?.type === 'assign'" @close="ui.modal = null">
        <p>press a key to assign</p>
      </Modal>
      <Modal :isOpen="ui.modal?.type === 'copy'" @close="ui.modal = null">
        <p>press a key to copy to</p>
      </Modal>
      <Modal :isOpen="ui.loading">
        <p>LOADING...</p>
      </Modal>
    </section>
  </main>
</template>

// src/react/app.tsx
import { useEffect, useState } from "react";
import { useLocalStorageState } from "./hooks";
import { Modal } from "./Modal";
import { Loader } from "./loader";
import { Provider, atom, useAtom, useSetAtom } from "jotai";
import { useAppState, useSamples } from "./state";
import { SampleWave } from "./viz";

export type BufferState = { [name: string]: AudioBuffer };

export type SampleT = {
  key: string;
  begin: number;
  active: boolean;
  bufferid: string;
};
export type SamplesT = {
  [id: string]: SampleT | null;
};

const ALLKEYS = "qwertyuiopasdfghjklzxcvbnm1234567890";

export default function Wrapper() {
  return (
    <Provider>
      <App />
    </Provider>
  );
}
export function App() {
  const [buffers, setBuffers] = useState<BufferState>({});
  const [loading, setLoading] = useState(false);
  const [state, setState] = useAppState();
  const [samples, setSamples] = useSamples();
  const [modal, setModal] = useState({ type: "", value: "" });

  useEffect(() => {
    const keydown = (ev: KeyboardEvent) => {
      const { key } = ev;
      console.log({ key });

      if (ALLKEYS.includes(key)) {
        // SAMPLE KEY
        // setEdit(key);
      }

      if (key.startsWith("Arrow")) {
        // ARROW KEYS
        return;
      }
    };

    const keyup = (ev: KeyboardEvent) => {
      const { key } = ev;
    };

    window.addEventListener("keydown", keydown);
    window.addEventListener("keyup", keyup);

    return () => {
      window.removeEventListener("keydown", keydown);
      window.removeEventListener("keyup", keyup);
    };
  }, []);

  const { edit } = state;
  const editingSample = samples[edit];

  return (
    <div className=" max-w-[1000px] mx-auto">
      <header>
        <h1 className=" my-2 text-2xl">Audio-Sampler</h1>
      </header>
      <main className=" h-[calc(100vh-60px)] grid grid-rows-[1fr_auto] gap-10 ">
        {!edit && (
          <section>
            <Loader setBuffers={setBuffers} setLoading={setLoading} />
            <div>
              <h2>Sources</h2>
              <ul className=" list-disc pl-5">
                {Object.entries(buffers).map(([bufferId, buffer]) => (
                  <li key={bufferId}>
                    <span className=" ">{bufferId}</span>
                    <button
                      className=" bg-white text-black "
                      onClick={() =>
                        setModal({
                          type: "assign",
                          value: bufferId,
                        })
                      }
                    >
                      assign
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          </section>
        )}
        {editingSample?.active && (
          <section>
            <div className="flex justify-between">
              <h2>EDITIING {edit}</h2>
              <button onClick={() => setState((st) => ({ ...st, edit: "" }))}>
                close
              </button>
            </div>
            <p>{JSON.stringify(editingSample)}</p>
            <Preview
              sample={editingSample}
              bufferId={editingSample.bufferid}
              buffer={buffers[editingSample.bufferid]}
            />
          </section>
        )}
        <Keyboard />
      </main>
      <Modal isOpen={loading}>
        <div className=" bg-[var(--b2)]">
          <p className=" text-3xl">LOADING....</p>
        </div>
      </Modal>

      <Modal isOpen={modal.type === "assign"}>
        <div className=" bg-[var(--b2)]">
          <h2>Assign sample to key</h2>
          <p>{modal.value}</p>
          <p className=" ">press key to assign</p>
        </div>
      </Modal>

      <Footer />
    </div>
  );
}

const Preview = ({
  bufferId,
  buffer,
  sample,
}: {
  bufferId: string;
  // edit: string;
  buffer: AudioBuffer;
  sample: SampleT;
  // callback: (type: string, val: any) => void;
  // removeBuffer: (id: string) => void;
}) => {
  const [wavebuffer, setWavebuffer] = useState<number[] | null>(null);
  useEffect(() => {
    // calc wavebuffer for viz
    const audioData = buffer.getChannelData(0);
    const chunkSize = buffer.sampleRate / 1000;
    const chunks = audioData.length / chunkSize;
    let last = 0;

    const wave = [];
    for (let x = 1; x < chunks; x++) {
      const to = Math.floor(chunkSize * x);
      const slice = audioData.slice(last, to);
      const max = findmax(slice);
      wave.push(max);
      last = to + 1;
    }
    setWavebuffer(wave);
  }, [buffer]);

  return (
    <div>
      <SampleWave sample={sample} wave={wavebuffer} buffer={buffer} />
    </div>
  );
};

export const findmax = (arr: Float32Array | number[]) => {
  let max = 0;
  arr.forEach((v) => {
    const x = Math.abs(v);
    if (x > max) max = x;
  });
  return max;
};

const Keyboard = () => {
  const [samples, setSamples] = useSamples();

  return (
    <section>
      <div className=" flex flex-col gap-1 ">
        <div className=" ml-[0vw] flex gap-1 ">
          {"qwertyuiop".split("").map((k) => (
            <Key key={k} letter={k} sample={samples[k]} />
          ))}
        </div>
        <div className=" ml-[2vw] flex gap-1">
          {"asdfghjkl".split("").map((k) => (
            <Key key={k} letter={k} sample={samples[k]} />
          ))}
        </div>
        <div className=" ml-[5vw] flex gap-1">
          {"zxcvbnm".split("").map((k) => (
            <Key key={k} letter={k} sample={samples[k]} />
          ))}
        </div>
      </div>
    </section>
  );
};

const Key = ({
  letter,
  sample,
}: {
  letter: string;
  sample: SampleT | null;
}) => {
  const [state, setState] = useAppState();
  const [samples] = useSamples();

  return (
    <button
      className=" w-[min(7vw,10vh)] border border-white aspect-square"
      onClick={() => {
        if (samples[letter]?.active)
          setState((st) => ({ ...st, edit: letter }));
      }}
    >
      {letter}
    </button>
  );
};

const Footer = () => (
  <footer className=" mt-[200px] max-w-[1000px] mx-auto">
    <p>
      DO NOT USE WITH BLUETOOTH, only wired speakers. BT speakers can add extra
      delay and ruin the responsiveness.
    </p>
    <p className=" my-3 text-center">
      Made open-source with 💙 for the web, by &nbsp;
      <a
        href="https://britnell.github.io/portfolio/about/"
        target="_blank"
        rel="noreferrer"
        className=" underline"
      >
        Britnell
      </a>
      - &nbsp;
      <br />
      <a
        href="https://github.com/Britnell/astro-gym/blob/main/src/react/loader.tsx"
        target="_blank"
        rel="noreferrer"
        className=" underline"
      >
        code on github
      </a>{" "}
      - feedback welcome
    </p>
  </footer>
);
