// src/vue/loader.vue
<script setup lang="ts">
import { defineProps, toRefs, onMounted, ref } from "vue";
import { loadFileBuffer, loadUriBuffer } from "./audio";
import { samplesDbWrite } from "./indexdb";
import { loadCachedSamples } from "./lib";
import { drums } from "./drums";
// const emit = defineEmits([]);

const props = defineProps(["buffers", "ui"]);
const { ui, buffers } = toRefs(props);

onMounted(async () => {
  if (!ui || !buffers) return;
  // Load cache
  ui.value.loading = true;
  const srcs = await loadCachedSamples();
  // if (srcs) buffers.value = srcs;
  if (srcs)
    Object.entries(srcs).map(([name, buffer]) => {
      buffers.value[name] = buffer;
    });
  ui.value.loading = false;
});

const loadFile = async (file: File | undefined) => {
  if (!file || !buffers || !ui) return;
  // setLoading(true);
  ui.value.loading = true;

  // read
  const buffer = await loadFileBuffer(file);
  if (buffer) buffers.value[file.name] = buffer;
  // cache
  const blob = new Blob([file], { type: file.type });
  await samplesDbWrite(blob, file.name).catch((err) => console.error(err));
  ui.value.loading = false;
};

const fileSelect = (ev: Event) => {
  const ip = ev.target as HTMLInputElement;
  loadFile(ip.files?.[0]);
};

const loadUri = async (uri: string) => {
  if (!buffers || !ui) return;

  ui.value.loading = true;
  const { blob, audioBuffer } = await loadUriBuffer(uri);
  if (audioBuffer) buffers.value[uri] = audioBuffer;

  if (blob) await samplesDbWrite(blob, uri).catch((err) => console.error(err));
  ui.value.loading = false;
};
const loadFromUrl = (ev: Event) => {
  const uri = (ev.target as HTMLFormElement).url?.value;
  if (uri) loadUri(uri);
};
</script>
<template>
  <div class="">
    <div class="border border-white p-4">
      <h2 class="text-xl font-bold">load audio</h2>
      <div className=" grid grid-cols-3 gap-10 ">
        <div class="">
          <label className=" mb-3 block" for="fileip">load local file :</label>
          <input
            id="fileip"
            type="file"
            accept="audio/mp3"
            @change="fileSelect"
          />
        </div>
        <div class="">
          <label for="urlip" className=" mb-3 block">load from url :</label>
          <form @submit.prevent="loadFromUrl">
            <input
              id="urlip"
              type="text"
              name="url"
              className=" bg-transparent border border-[var(--b2)] "
            />
            <button className="primary ">load</button>
          </form>
        </div>
        <div class="x">
          <p>
            Play rhythm roulette & get a random song for the LOC records :
            <a
              href="/api/random"
              className="underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              Random
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

// src/react/loader.tsx
import { useEffect, useState, type FormEvent } from "react";
import Player, { Modal } from "./player";

/* 
  TODO
  -X delete key modal
  -X copy key
  -X sample speed
  - sample edit modal (popup arrowkeys move beginning)
  - click to seek
  - zoom waveform
  - [ ] Set sample length & play until end
*/

export const audioContext = new (window.AudioContext ||
  window.webkitAudioContext)();

export const loadSource = (buffer: AudioBuffer | void, speed: number = 1.0) => {
  if (!buffer) return null;
  const source = audioContext.createBufferSource();
  source.buffer = buffer;
  source.playbackRate.value = speed;
  source.connect(audioContext.destination);
  return source;
};

export default function Loader() {
  const [buffers, setBuffers] = useState<BufferState>({});
  const [demo, setDemo] = useState<string | undefined>(undefined);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // load files from db
    const load = async () => {
      const blobs = await samplesDbReadAll().catch((e) => {
        console.error(e);
        return;
      });
      if (!blobs) return;

      const srcs: BufferState = {};
      setLoading(true);
      await Promise.all(
        Object.entries(blobs).map(async ([name, blob]) => {
          // load array from blob
          const arrayBuffer = await blob.arrayBuffer();
          const buffer = await audioContext
            .decodeAudioData(arrayBuffer)
            .catch((err) => console.error("err decode", err, name));
          if (!buffer) return;
          srcs[name] = buffer;
          return buffer;
        })
      );

      setLoading(false);
      setBuffers(srcs);
    };
    load();
  }, []);

  const loadFile = (file: File | undefined) => {
    if (!file) return;

    setLoading(true);
    const reader = new FileReader();
    reader.onload = async (ev) => {
      // Load buffer
      const arrayBuffer = ev.target?.result as ArrayBuffer;
      const buffer = await audioContext.decodeAudioData(arrayBuffer);
      setBuffers((s) => ({ ...s, [file.name]: buffer }));

      // store in db
      const blob = new Blob([file], { type: file.type });
      await samplesDbWrite(blob, file.name).catch((err) => console.error(err));
      setLoading(false);
    };
    reader.readAsArrayBuffer(file);
  };

  const removeBuffer = (bufferid: string) => {
    const _buffers = { ...buffers };
    delete _buffers[bufferid];
    setBuffers(_buffers);
    // rmv in local storage
    samplesDbRemove(bufferid);
  };

  const loadUri = async (uri: string) => {
    setLoading(true);
    const blob = await fetch(uri).then((res) => res.blob());
    const arrayBuffer = await blob.arrayBuffer();
    const audioBuffer = await audioContext.decodeAudioData(arrayBuffer);
    setBuffers((s) => ({ ...s, [uri]: audioBuffer }));
    await samplesDbWrite(blob, uri).catch((err) => console.error(err));
    setLoading(false);
  };

  const loadFromUrl = async (ev: FormEvent) => {
    ev.preventDefault();
    const uri = (ev.target as HTMLFormElement).url.value;
    loadUri(uri);
  };

  const loadDemo = async () => {
    if (!selectedDemo) return;
    loadUri(selectedDemo.url);
  };

  const selectedDemo = demoSamples.find((d) => d.name === demo);

  return (
    <>
      <header className=" max-w-[1000px] mx-auto">
        <h1 className=" my-2 text-2xl">Audio-Sampler</h1>
        <h2 className=" mt-8 text-xl pl-4">Add source files</h2>
        <div className="  p-4 bg-[#282dbd] bg-opacity-5">
          <div className=" grid grid-cols-3 gap-10">
            <label>
              <span className=" mb-3 block">load local file :</span>
              <input
                type="file"
                accept="audio/mp3"
                onChange={(ev) => {
                  const ip = ev.target as HTMLInputElement;
                  loadFile(ip.files?.[0]);
                }}
              />
            </label>
            <label>
              <span className=" mb-3 block">load from url :</span>
              <form onSubmit={loadFromUrl}>
                <input
                  type="text"
                  name="url"
                  className=" bg-transparent border border-[var(--b2)] "
                />
                <button className=" bg-white text-[var(--bg)]">load</button>
              </form>
            </label>
            <div>
              <p>
                Play rhythm roulette & get a random song for the LOC records
              </p>
              <a
                href="/api/random"
                className="underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Random
              </a>
            </div>
          </div>
        </div>
      </header>
      <main>
        <Player buffers={buffers} removeBuffer={removeBuffer} />
      </main>
      <Modal isOpen={loading}>
        <div className=" bg-[var(--b2)]">
          <p className=" text-3xl">LOADING....</p>
        </div>
      </Modal>
      <footer className=" mt-[200px] max-w-[1000px] mx-auto">
        <p>
          DO NOT USE WITH BLUETOOTH, only wired speakers. BT speakers can add
          extra delay and ruin the responsiveness.
        </p>
        <p className=" my-3 text-center">
          Made open-source with 💙 for the web, by &nbsp;
          <a
            href="https://britnell.github.io/portfolio/about/"
            target="_blank"
            rel="noreferrer"
            className=" underline"
          >
            Britnell
          </a>
          - &nbsp;
          <br />
          <a
            href="https://github.com/Britnell/astro-gym/blob/main/src/react/loader.tsx"
            target="_blank"
            rel="noreferrer"
            className=" underline"
          >
            code on github
          </a>{" "}
          - feedback welcome
        </p>
      </footer>
    </>
  );
}

// ================================

const DB_NAME = "web-sampler";
const STORE_NAME = "samples-cache";

async function getDbStore(): Promise<IDBObjectStore | string> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);

    req.onupgradeneeded = () => {
      const db = req.result;
      db.createObjectStore(STORE_NAME);
    };

    req.onsuccess = async () => {
      const db = req.result;
      const transaction = db.transaction([STORE_NAME], "readwrite");
      transaction.onerror = (ev) => {
        console.error(ev);
        reject("transaction error ");
      };

      const objectStore = transaction.objectStore(STORE_NAME);
      resolve(objectStore);
    };

    req.onerror = (ev) => {
      console.error(ev);
      reject("db req error ");
    };
  });
}

function samplesDbWrite(blob: Blob, filename: string) {
  return new Promise(async (resolve, reject) => {
    const objectStore = await getDbStore();
    if (typeof objectStore === "string") {
      reject(objectStore);
      return;
    }
    const req = objectStore.put(blob, filename);
    req.onsuccess = () => {
      resolve({ success: true });
    };
    req.onerror = (ev) => {
      console.error(ev);
      reject("req error ");
    };
  });
}

function samplesDbRemove(filename: string) {
  return new Promise(async (resolve, reject) => {
    const objectStore = await getDbStore();
    if (typeof objectStore === "string") {
      reject(objectStore);
      return;
    }
    const req = objectStore.delete(filename);
    req.onsuccess = () => {
      resolve({ success: true });
    };
    req.onerror = (ev) => {
      console.error(ev);
      reject("req error ");
    };
  });
}

function samplesDbReadAll(): Promise<{ [key: string]: Blob }> {
  return new Promise(async (resolve, reject) => {
    const objectStore = await getDbStore();
    if (typeof objectStore === "string") {
      reject(objectStore);
      return;
    }

    const req = objectStore.openCursor(); // Use a cursor for large datasets

    req.onerror = (ev) => {
      console.error(ev);
      reject(" cursor error ");
    };

    const samples: { [key: string]: any } = {};

    req.onsuccess = () => {
      const cursor = req.result;
      if (cursor) {
        if (typeof cursor.key === "string") {
          samples[cursor.key] = cursor.value;
        }
        cursor.continue();
        return;
      }
      resolve(samples);
    };
  });
}

declare global {
  interface Window {
    webkitAudioContext: typeof AudioContext;
  }
}

export type BufferState = { [name: string]: AudioBuffer };

const demoSamples = [
  {
    name: "The Father, The Son, and The Harold Rubin",
    url: "/The-Harold-Rubin.mp3",
    source:
      "https://freemusicarchive.org/music/Harold_Rubin_Ehran_Elisha__Haim_Elisha/East_Of_Jaffa/02_East_Of_Jaffa_-_The_Father_The/",
  },
  {
    name: "Song for Bilbao",
    url: "/Song-for-Bilbao.mp3",
    source:
      "https://freemusicarchive.org/music/Jazz_at_Mladost_Club/Jazz_Night/Song_for_Bilbao/",
  },
];
